lenguage: node_js

node_js:
  - "node"

script:
  - npm run clean-force
  - npm run remove-modules
  - npm run install-npm
  - npm run audit-fix

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
