lenguage: node_js

node_js:
  - "node"

script:
  - npm i
  - npm run build

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
