executors:
  buildpack_deps:
    docker:
      - image: circleci/buildpack-deps
jobs:
  deploy_ghpages:
    executor: buildpack_deps
    steps:
      - checkout
      - run: bash deploy.sh
      - gh-pages/deploy:
          ssh-fingerprints: 'ff:22:gs:v6:gg:2g:22:7j:73:gf:ja:36:ff:y2:22:89'
version: 2.1
workflows:
  build_deploy:
    jobs:
      - deploy_ghpages